export const testSchedule = {
  startDate: "26.01.2026",
  endDate: "17.05.2026",
  startExamsDate: "18.05.2026",
  endExamsDate: "04.06.2026",
  employeeDto: null,
  studentGroupDto: {
    name: "351004",
    facultyId: 20026,
    facultyAbbrev: "ФКСиС",
    facultyName: "Факультет компьютерных систем и сетей",
    specialityDepartmentEducationFormId: 20642,
    specialityName: "Программная инженерия",
    specialityAbbrev: "ПИ",
    course: 3,
    id: 24133,
    calendarId: "uqhu7o4lsekvip1426gl1i88bo@group.calendar.google.com",
    educationDegree: 1,
  },
  schedules: {
    Суббота: [
      {
        auditories: ["216-4 к."],
        endLessonTime: "09:55",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 0,
        startLessonTime: "08:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [4],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "14.02.2026",
        endLessonDate: "09.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["310-4 к."],
        endLessonTime: "11:30",
        lessonTypeAbbrev: "ЛК",
        note: "для группы 351004",
        numSubgroup: 0,
        startLessonTime: "10:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [2, 4],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "31.01.2026",
        endLessonDate: "09.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "13:25",
        lessonTypeAbbrev: "ЛК",
        note: "31.01 в СЭО",
        numSubgroup: 0,
        startLessonTime: "12:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РПОдМП",
        subjectFullName:
          "Разработка программного обеспечения для мобильных платформ",
        weekNumber: [2, 4],
        employees: [
          {
            id: 500572,
            firstName: "Евгений",
            middleName: "Николаевич",
            lastName: "Базылев",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500572",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "e.bazylev@bsuir.by",
            urlId: "e-bazylev",
            calendarId: "i5ql141n994i85ocii8hh48348@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "31.01.2026",
        endLessonDate: "09.05.2026",
        announcement: false,
        split: true,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "15:00",
        lessonTypeAbbrev: "ЛК",
        note: "31.01 в СЭО",
        numSubgroup: 0,
        startLessonTime: "13:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РПОдМП",
        subjectFullName:
          "Разработка программного обеспечения для мобильных платформ",
        weekNumber: [2, 4],
        employees: [
          {
            id: 500572,
            firstName: "Евгений",
            middleName: "Николаевич",
            lastName: "Базылев",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500572",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "e.bazylev@bsuir.by",
            urlId: "e-bazylev",
            calendarId: "i5ql141n994i85ocii8hh48348@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "31.01.2026",
        endLessonDate: "09.05.2026",
        announcement: false,
        split: true,
      },
    ],
    Четверг: [
      {
        auditories: ["318-4 к."],
        endLessonTime: "15:00",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "13:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ОБиПвСИТ",
        subjectFullName:
          "Основы бизнеса и права в сфере инфокоммуникационных технологий",
        weekNumber: [2, 4],
        employees: [
          {
            id: 510631,
            firstName: "Елена",
            middleName: "Игоревна",
            lastName: "Орлова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/510631",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: null,
            urlId: "e-orlova",
            calendarId: "ebmf17rqrhc2p961dqn1d1ml0c@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "29.01.2026",
        endLessonDate: "07.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: [],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ФизК",
        subjectFullName: "Физическая культура",
        weekNumber: [1, 2, 3, 4],
        employees: [],
        dateLesson: null,
        startLessonDate: "29.01.2026",
        endLessonDate: "14.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ОБиПвСИТ",
        subjectFullName:
          "Основы бизнеса и права в сфере инфокоммуникационных технологий",
        weekNumber: [1, 2, 3, 4],
        employees: [
          {
            id: 510631,
            firstName: "Елена",
            middleName: "Игоревна",
            lastName: "Орлова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/510631",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: null,
            urlId: "e-orlova",
            calendarId: "ebmf17rqrhc2p961dqn1d1ml0c@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "29.01.2026",
        endLessonDate: "14.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "АКГ",
        subjectFullName: "Алгоритмы компьютерной графики",
        weekNumber: [2, 3, 4],
        employees: [
          {
            id: 511984,
            firstName: "Павел",
            middleName: "Николаевич",
            lastName: "Красковский",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/511984",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "kraskovskij@bsuir.by",
            urlId: "p-kraskovskij",
            calendarId: "45iurev5eb8phtvo1o1idc8294@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "29.01.2026",
        endLessonDate: "07.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ОБиПвСИТ",
        subjectFullName:
          "Основы бизнеса и права в сфере инфокоммуникационных технологий",
        weekNumber: [1],
        employees: [
          {
            id: 510631,
            firstName: "Елена",
            middleName: "Игоревна",
            lastName: "Орлова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/510631",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: null,
            urlId: "e-orlova",
            calendarId: "ebmf17rqrhc2p961dqn1d1ml0c@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "19.02.2026",
        endLessonDate: "14.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["106-4 к."],
        endLessonTime: "22:00",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "20:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "АКГ",
        subjectFullName: "Алгоритмы компьютерной графики",
        weekNumber: [1],
        employees: [
          {
            id: 511984,
            firstName: "Павел",
            middleName: "Николаевич",
            lastName: "Красковский",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/511984",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "kraskovskij@bsuir.by",
            urlId: "p-kraskovskij",
            calendarId: "45iurev5eb8phtvo1o1idc8294@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "19.02.2026",
        endLessonDate: "14.05.2026",
        announcement: false,
        split: false,
      },
    ],
    Пятница: [
      {
        auditories: ["epam 401-1-2 к."],
        endLessonTime: "11:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "10:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "БД",
        subjectFullName: "Базы данных",
        weekNumber: [2],
        employees: [],
        dateLesson: null,
        startLessonDate: "30.01.2026",
        endLessonDate: "24.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["epam 401-1-2 к."],
        endLessonTime: "11:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "10:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "БД",
        subjectFullName: "Базы данных",
        weekNumber: [4],
        employees: [],
        dateLesson: null,
        startLessonDate: "13.02.2026",
        endLessonDate: "08.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["epam 401-1-2 к."],
        endLessonTime: "13:25",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "12:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "БД",
        subjectFullName: "Базы данных",
        weekNumber: [2],
        employees: [],
        dateLesson: null,
        startLessonDate: "30.01.2026",
        endLessonDate: "24.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["epam 401-1-2 к."],
        endLessonTime: "13:25",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "12:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "БД",
        subjectFullName: "Базы данных",
        weekNumber: [4],
        employees: [],
        dateLesson: null,
        startLessonDate: "13.02.2026",
        endLessonDate: "08.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "АКГ",
        subjectFullName: "Алгоритмы компьютерной графики",
        weekNumber: [3],
        employees: [
          {
            id: 511984,
            firstName: "Павел",
            middleName: "Николаевич",
            lastName: "Красковский",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/511984",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "kraskovskij@bsuir.by",
            urlId: "p-kraskovskij",
            calendarId: "45iurev5eb8phtvo1o1idc8294@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "06.02.2026",
        endLessonDate: "01.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "АКГ",
        subjectFullName: "Алгоритмы компьютерной графики",
        weekNumber: [1],
        employees: [
          {
            id: 511984,
            firstName: "Павел",
            middleName: "Николаевич",
            lastName: "Красковский",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/511984",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "kraskovskij@bsuir.by",
            urlId: "p-kraskovskij",
            calendarId: "45iurev5eb8phtvo1o1idc8294@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "20.02.2026",
        endLessonDate: "15.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "СПП",
        subjectFullName: "Современные платформы программирования",
        weekNumber: [1, 3],
        employees: [
          {
            id: 532092,
            firstName: "Вита",
            middleName: "Владленовна",
            lastName: "Петровская",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/532092",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "v.petrovskaia@bsuir.by",
            urlId: "v-petrovskaia",
            calendarId: "07s1f23k4t94iseiachhtg4kss@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "06.02.2026",
        endLessonDate: "15.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "22:00",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "20:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "СПП",
        subjectFullName: "Современные платформы программирования",
        weekNumber: [3],
        employees: [
          {
            id: 532092,
            firstName: "Вита",
            middleName: "Владленовна",
            lastName: "Петровская",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/532092",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "v.petrovskaia@bsuir.by",
            urlId: "v-petrovskaia",
            calendarId: "07s1f23k4t94iseiachhtg4kss@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "06.02.2026",
        endLessonDate: "01.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "22:00",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "20:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "СПП",
        subjectFullName: "Современные платформы программирования",
        weekNumber: [1],
        employees: [
          {
            id: 532092,
            firstName: "Вита",
            middleName: "Владленовна",
            lastName: "Петровская",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/532092",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "v.petrovskaia@bsuir.by",
            urlId: "v-petrovskaia",
            calendarId: "07s1f23k4t94iseiachhtg4kss@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "20.02.2026",
        endLessonDate: "15.05.2026",
        announcement: false,
        split: false,
      },
    ],
    Понедельник: [
      {
        auditories: ["213б-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РВ",
        subjectFullName: "Распределенные вычисления",
        weekNumber: [3],
        employees: [
          {
            id: 500579,
            firstName: "Галина",
            middleName: "Владимировна",
            lastName: "Данилова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500579",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "danilova_poit@bsuir.by",
            urlId: "g-danilova",
            calendarId: "5busnevj7cj5214q3m6qqim8f4@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "02.02.2026",
        endLessonDate: "27.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РВ",
        subjectFullName: "Распределенные вычисления",
        weekNumber: [1],
        employees: [
          {
            id: 500579,
            firstName: "Галина",
            middleName: "Владимировна",
            lastName: "Данилова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500579",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "danilova_poit@bsuir.by",
            urlId: "g-danilova",
            calendarId: "5busnevj7cj5214q3m6qqim8f4@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "16.02.2026",
        endLessonDate: "11.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["216-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РПОдМП",
        subjectFullName:
          "Разработка программного обеспечения для мобильных платформ",
        weekNumber: [3],
        employees: [
          {
            id: 500572,
            firstName: "Евгений",
            middleName: "Николаевич",
            lastName: "Базылев",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500572",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "e.bazylev@bsuir.by",
            urlId: "e-bazylev",
            calendarId: "i5ql141n994i85ocii8hh48348@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "02.02.2026",
        endLessonDate: "27.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["216-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РПОдМП",
        subjectFullName:
          "Разработка программного обеспечения для мобильных платформ",
        weekNumber: [1],
        employees: [
          {
            id: 500572,
            firstName: "Евгений",
            middleName: "Николаевич",
            lastName: "Базылев",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500572",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "e.bazylev@bsuir.by",
            urlId: "e-bazylev",
            calendarId: "i5ql141n994i85ocii8hh48348@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "16.02.2026",
        endLessonDate: "11.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["319-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ОБиПвСИТ",
        subjectFullName:
          "Основы бизнеса и права в сфере инфокоммуникационных технологий",
        weekNumber: [1, 3],
        employees: [
          {
            id: 510631,
            firstName: "Елена",
            middleName: "Игоревна",
            lastName: "Орлова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/510631",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: null,
            urlId: "e-orlova",
            calendarId: "ebmf17rqrhc2p961dqn1d1ml0c@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "02.02.2026",
        endLessonDate: "11.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["319-4 к."],
        endLessonTime: "22:00",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "20:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ОБиПвСИТ",
        subjectFullName:
          "Основы бизнеса и права в сфере инфокоммуникационных технологий",
        weekNumber: [1, 3],
        employees: [
          {
            id: 510631,
            firstName: "Елена",
            middleName: "Игоревна",
            lastName: "Орлова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/510631",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: null,
            urlId: "e-orlova",
            calendarId: "ebmf17rqrhc2p961dqn1d1ml0c@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "02.02.2026",
        endLessonDate: "11.05.2026",
        announcement: false,
        split: false,
      },
    ],
    Вторник: [
      {
        auditories: [],
        endLessonTime: "15:00",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "13:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ФизК",
        subjectFullName: "Физическая культура",
        weekNumber: [1, 2, 3, 4],
        employees: [],
        dateLesson: null,
        startLessonDate: "27.01.2026",
        endLessonDate: "12.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["209-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "СПП",
        subjectFullName: "Современные платформы программирования",
        weekNumber: [1, 2, 3, 4],
        employees: [
          {
            id: 500601,
            firstName: "Дмитрий",
            middleName: "Андреевич",
            lastName: "Сурков",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500601",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "d.surkov@bsuir.by",
            urlId: "d-surkov",
            calendarId: "ki8a1kl74kggs8ikhrre2nuq70@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "27.01.2026",
        endLessonDate: "12.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213б-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 0,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "СПП",
        subjectFullName: "Современные платформы программирования",
        weekNumber: [2],
        employees: [
          {
            id: 532092,
            firstName: "Вита",
            middleName: "Владленовна",
            lastName: "Петровская",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/532092",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "v.petrovskaia@bsuir.by",
            urlId: "v-petrovskaia",
            calendarId: "07s1f23k4t94iseiachhtg4kss@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "27.01.2026",
        endLessonDate: "21.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213а-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [3],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "03.02.2026",
        endLessonDate: "28.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["301-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "К.Ч.",
        subjectFullName: "Кураторский, информационный час",
        weekNumber: [4],
        employees: [
          {
            id: 500624,
            firstName: "Ирина",
            middleName: "Михайловна",
            lastName: "Ратникова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500624",
            degree: "кандидат философских наук",
            degreeAbbrev: "к.ф.н.",
            rank: "доцент",
            email: "ratnikova@bsuir.by",
            urlId: "i-ratnikova",
            calendarId: "il97sv094fir7hjcb34l807i38@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "10.02.2026",
        endLessonDate: "05.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213а-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [1],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "17.02.2026",
        endLessonDate: "12.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213а-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ЛК",
        note: "для группы 351004",
        numSubgroup: 0,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [2],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "27.01.2026",
        endLessonDate: "21.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213а-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 2,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [3],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "03.02.2026",
        endLessonDate: "28.04.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["213а-4 к."],
        endLessonTime: "20:25",
        lessonTypeAbbrev: "ЛР",
        note: null,
        numSubgroup: 1,
        startLessonTime: "19:00",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [1],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "17.02.2026",
        endLessonDate: "12.05.2026",
        announcement: false,
        split: false,
      },
    ],
    Среда: [
      {
        auditories: ["108-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ЛК",
        note: "для групп 351001-3",
        numSubgroup: 0,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ПОЦП",
        subjectFullName: "Программное обеспечение цифрового проектирования",
        weekNumber: [1, 2, 3, 4],
        employees: [
          {
            id: 500304,
            firstName: "Александр",
            middleName: "Александрович",
            lastName: "Иванюк",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500304",
            degree: "доктор технических наук",
            degreeAbbrev: "д.т.н.",
            rank: null,
            email: "ivaniuk@bsuir.by",
            urlId: "a-ivaniuk",
            calendarId: "rhfb8nhigotc7ls030abdr3ajs@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "28.01.2026",
        endLessonDate: "13.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["319-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ПЗ",
        note: null,
        numSubgroup: 0,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "Инф. час",
        subjectFullName: "Информационный час",
        weekNumber: [1, 2, 3],
        employees: [
          {
            id: 500624,
            firstName: "Ирина",
            middleName: "Михайловна",
            lastName: "Ратникова",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/500624",
            degree: "кандидат философских наук",
            degreeAbbrev: "к.ф.н.",
            rank: "доцент",
            email: "ratnikova@bsuir.by",
            urlId: "i-ratnikova",
            calendarId: "il97sv094fir7hjcb34l807i38@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "28.01.2026",
        endLessonDate: "13.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["218-4 к."],
        endLessonTime: "16:55",
        lessonTypeAbbrev: "ЛК",
        note: "для группы 351004",
        numSubgroup: 0,
        startLessonTime: "15:30",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "ГДиКвПИ",
        subjectFullName:
          "Групповая динамика и коммуникация в программной инженерии",
        weekNumber: [4],
        employees: [
          {
            id: 551391,
            firstName: "Анастасия",
            middleName: "Евгеньевна",
            lastName: "Клебан",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/551391",
            degree: "",
            degreeAbbrev: "",
            rank: null,
            email: "a.kleban@bsuir.by",
            urlId: "a-kleban",
            calendarId:
              "da1dd7b4c9b03ba06f97c88cf8d6714e6298467875e8b7fa5bda9cee68f2740f@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "11.02.2026",
        endLessonDate: "06.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: ["108-4 к."],
        endLessonTime: "18:30",
        lessonTypeAbbrev: "ЛК",
        note: null,
        numSubgroup: 0,
        startLessonTime: "17:05",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "РВ",
        subjectFullName: "Распределенные вычисления",
        weekNumber: [1, 2, 3, 4],
        employees: [
          {
            id: 505984,
            firstName: "Александр",
            middleName: "Геннадиевич",
            lastName: "Хмелев",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/505984",
            degree: "доктор экономических наук",
            degreeAbbrev: "д.э.н.",
            rank: "доцент",
            email: "akhmelev@bsuir.by",
            urlId: "a-khmelev",
            calendarId: "nt1mr16oet8vuicl3d7l304o9g@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "28.01.2026",
        endLessonDate: "13.05.2026",
        announcement: false,
        split: false,
      },
      {
        auditories: [],
        endLessonTime: "22:00",
        lessonTypeAbbrev: "ЛК",
        note: "точка доступа",
        numSubgroup: 0,
        startLessonTime: "20:35",
        studentGroups: [
          {
            specialityName: "Программная инженерия",
            specialityCode: "6-05-0612-01",
            numberOfStudents: 28,
            name: "351004",
            educationDegree: 1,
          },
        ],
        subject: "БД",
        subjectFullName: "Базы данных",
        weekNumber: [1, 2, 3, 4],
        employees: [
          {
            id: 504394,
            firstName: "Святослав",
            middleName: "Святославович",
            lastName: "Куликов",
            photoLink: "https://iis.bsuir.by/api/v1/employees/photo/504394",
            degree: "кандидат технических наук",
            degreeAbbrev: "к.т.н.",
            rank: "доцент",
            email: "kulikov@bsuir.by",
            urlId: "s-kulikov",
            calendarId: "uoln325vkhi30v5ovgfm58uflg@group.calendar.google.com",
            jobPositions: null,
            chief: false,
          },
        ],
        dateLesson: null,
        startLessonDate: "28.01.2026",
        endLessonDate: "13.05.2026",
        announcement: false,
        split: false,
      },
    ],
  },
  nextSchedules: null,
  currentTerm: "Весенний",
  nextTerm: null,
  exams: [],
  currentPeriod: "Весенний",
  isZaochOrDist: false,
};
